[tskv]
timeReStr = '\ttimestamp=(\d{4}-\d{2}-\d{2}T\d\d:\d\d:\d\d)\t'
timeLayout = "2006-01-02T15:04:05"

[java]
timeReStr = '^(\d{4}-\d{2}-\d{2} \d\d:\d\d:\d\d)'
timeLayout = "2006-01-02 15:04:05"

[kern]
timeReStr = '^(\d{4}-\d{2}-\d{2}T\d\d:\d\d:\d\d)'
timeLayout = "2006-01-02T15:04:05"

[apache]
timeReStr = '\[(\d{2}/\w{3}/\d{4}:\d{2}:\d{2}:\d{2})\s'
timeLayout = "02/Jan/2006:15:04:05"
bufSize = 8192
stepsLimit = 512

[nginx]
timeReStr = '\[(\d{2}/\w{3}/\d{4}:\d{2}:\d{2}:\d{2})\s'
timeLayout = "02/Jan/2006:15:04:05"
bufSize = 4096

[custom_app]
timeReStr = 'timestamp=(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})'
timeLayout = "2006-01-02T15:04:05"
bufSize = 16384
stepsLimit = 1024
