name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          # Create dist directory
          mkdir -p dist

          # Build for Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/ttail-linux-amd64 ./cmd/ttail

          # Build for Linux ARM64
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/ttail-linux-arm64 ./cmd/ttail

          # Build for Windows AMD64
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/ttail-windows-amd64.exe ./cmd/ttail

          # Build for macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/ttail-darwin-amd64 ./cmd/ttail

          # Build for macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/ttail-darwin-arm64 ./cmd/ttail

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/ttail-linux-amd64
            dist/ttail-linux-arm64
            dist/ttail-windows-amd64.exe
            dist/ttail-darwin-amd64
            dist/ttail-darwin-arm64
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
